### ISSUE TITLE
Walkoff installation on Ubuntu not working.

### ISSUE THREAD

**Issue by flutterhack42** [nsacyber/WALKOFF#243]
Hello, I have tried to install Walkoff on Ubuntu Server 18.04. I followed the installation process after getting Docker, Docker-composer, and get-all. The ./build_bootloader.sh step seems to go with out error, however when I run ./walkoff.sh up --build it get the following output:

username@Ubuntu-Walkoff:~/WALKOFF$ sudo ./walkoff.sh up --build --debug
Starting Walkoff Bootloader...
OS detected as Linux, using 172.18.0.1 as target for locally-hosted services.
/home/username/WALKOFF/common/docker_helpers.py:314: RuntimeWarning: coroutine 'Docker._do_query' was never awaited
  if (await client._query("_ping")).status == 200:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2019-09-26 19:17:05,885 - UMPIRE - INFO:Docker connection closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/WALKOFF/bootloader/bootloader.py", line 543, in <module>
    asyncio.run(Bootloader.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/username/WALKOFF/bootloader/bootloader.py", line 322, in run
    async with aiohttp.ClientSession() as session, connect_to_aiodocker() as docker_client:
  File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/home/username/WALKOFF/common/docker_helpers.py", line 314, in connect_to_aiodocker
    if (await client._query("_ping")).status == 200:
TypeError: object _AsyncCM can't be used in 'await' expression

Any help would be greatly appreciated!!

**Comment by adpham95** [comment]
There was a change in the latest version of aiodocker. I've pinned the aiodocker version to 0.14.0 for now, a proper fix will come in the the next RC of WALKOFF which will be released in a couple weeks.

Please `git pull` and try again, let us know if you have any further issues.

**Comment by adpham95** [comment]
Sorry, seems I didn't actually push that change. It's pushed to master now.

**Comment by flutterhack42** [comment]
Thanks! It is working great now!!
