### ISSUE TITLE
docker_helpers.py:314: RuntimeWarning: coroutine 'Docker._do_query' was never awaited

### ISSUE THREAD

**Issue by zambomarcell** [nsacyber/WALKOFF#244]
Hi!

On Centos 7 with lastest docker CE edition, after git clone ...

I get the following error message:

`
[root@docker WALKOFF]# ./walkoff.sh up --build
OS detected as Linux, using 172.17.0.1 as target for locally-hosted services.
/root/WALKOFF/common/docker_helpers.py:314: RuntimeWarning: coroutine 'Docker._do_query' was never awaited
  if (await client._query("_ping")).status == 200:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2019-09-27 06:34:50,134 - UMPIRE - INFO:Docker connection closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/WALKOFF/bootloader/bootloader.py", line 543, in <module>
    asyncio.run(Bootloader.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/root/WALKOFF/bootloader/bootloader.py", line 322, in run
    async with aiohttp.ClientSession() as session, connect_to_aiodocker() as docker_client:
  File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/root/WALKOFF/common/docker_helpers.py", line 314, in connect_to_aiodocker
    if (await client._query("_ping")).status == 200:
TypeError: object _AsyncCM can't be used in 'await' expression
`

**Comment by adpham95** [comment]
There was a change in the latest version of aiodocker. I've pinned the aiodocker version to 0.14.0 for now, a proper fix will come in the the next RC of WALKOFF which will be released in a couple weeks.

Please `git pull` and try again, let us know if you have any further issues.

**Comment by zambomarcell** [comment]
Hi,

I tried, but no changes. Did you commit your changes?

**Comment by adpham95** [comment]
Sorry, that was my bad. Good to hear the replace worked, it's also pushed to master now.

**Comment by aoighost** [comment]
So I'm testing on Windows with the latest walkoff and this patch appears to have broken build on my windows box.
