### ISSUE TITLE
"aioredis.errors.AuthError: ERR Client sent AUTH, but no password is set"

### ISSUE THREAD

**Issue by ch40s** [nsacyber/WALKOFF#256]
Hey all, I'm using the arm image "redis:latest" and I get the following error, any idea how to troubleshoot and solve this?

```
$ docker service logs -f walkoff_core_umpire
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/umpire/umpire.py", line 360, in <module>
    debug=args.debug)
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/app/umpire/umpire.py", line 71, in run
    async with connect_to_aioredis_pool(config.REDIS_URI) as redis, aiohttp.ClientSession() as session, \
  File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/app/common/redis_helpers.py", line 16, in connect_to_aioredis_pool
    redis_pool = await aioredis.create_redis_pool(redis_uri, password=config.get_from_file(config.REDIS_KEY_PATH))
  File "/usr/local/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 198, in create_redis_pool
    loop=loop)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 133, in create_connection
    await conn.auth(password)
  File "/usr/local/lib/python3.7/site-packages/aioredis/util.py", line 52, in wait_ok
    res = await fut
aioredis.errors.AuthError: ERR Client sent AUTH, but no password is set
```

**Comment by ch40s** [comment]
I was able to resolve this by using a redis.conf file for the redis-service. 

bootloader/base-compose.yml : 

```
    volumes:
      - ./data/redis.conf:/etc/redis/redis.conf
```
