### ISSUE TITLE
"./walkoff.sh up -d" failed

### ISSUE THREAD

**Issue by yongquanf** [nsacyber/WALKOFF#263]
2020-04-21 03:52:50,704 - BOOTLOADER - INFO:Pulled image mongo:4.
2020-04-21 03:52:50,704 - BOOTLOADER - INFO:Pulling image mongo-express:latest
2020-04-21 04:07:22,150 - BOOTLOADER - INFO:Pulled image mongo-express:latest.
2020-04-21 04:07:22,150 - BOOTLOADER - INFO:Pulling image portainer/portainer:latest
2020-04-21 04:08:10,124 - BOOTLOADER - INFO:Pulled image portainer/portainer:latest.
2020-04-21 04:08:10,124 - BOOTLOADER - INFO:Deploying base services (registry, minio, mongo, portainer, redis)...
2020-04-21 04:08:10,144 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:11,166 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:13,193 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:17,200 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:25,227 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:35,259 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:45,270 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:08:55,308 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:09:05,335 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:09:15,333 - BOOTLOADER - INFO:Failed deploying, waiting to try again...
2020-04-21 04:09:15,334 - UMPIRE - INFO:Docker connection closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 45, in call
    result = await fn(*args, **kwargs)
  File "/WALKOFF/WALKOFF/bootloader/bootloader.py", line 234, in deploy_compose
    raise e
  File "/WALKOFF/WALKOFF/bootloader/bootloader.py", line 224, in deploy_compose
    stderr=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE)
  File "/usr/local/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1529, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 764, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/WALKOFF/WALKOFF/bootloader/bootloader.py", line 588, in <module>
    asyncio.run(Bootloader.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/WALKOFF/WALKOFF/bootloader/bootloader.py", line 356, in run
    await getattr(bootloader, args.command)()
  File "/WALKOFF/WALKOFF/bootloader/bootloader.py", line 455, in up
    await deploy_compose(base_compose)
  File "/usr/local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 42, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f74f2c22410 state=finished raised FileNotFoundError>

**Comment by yongquanf** [comment]
After I changed back the apt-get source from ubuntu to debian, the problem is solved.
